name: CI - Backend Product API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        PYTHONPATH=. pytest

    - name: Run Linter
      run: |
        flake8 app/

    - name: Build Docker Image
      run: |
        docker build -t backend-product-api:latest .
